### ISSUE TITLE
[@nuxtjs/algolia] Passing searchClient from useAlgoliaRef triggers a 500 error

### ISSUE THREAD

**Issue by Rigo-m** [atoms-studio/nuxt-swiftsearch#1]
https://github.com/Rigo-m/test-swiftsearch/tree/main/pages

index.vue works in SSR, nuxt-algolia.vue page throws a 500

@baroshem can you give it a look?

**Comment by Rigo-m** [comment]
@Baroshem dependency problem should be fixed with new module release :)
Here's the working stackblitz anyway https://stackblitz.com/github/rigo-m/test-swiftsearch?file=README.md

**Comment by Baroshem** [comment]
Hey @Rigo-m 

I have checked that the generation of the AlgoliaRef works correctly from the NuxtAlgolia module so the issue is not related to the module itself but rather how it is used by next elements (instantsearch).

The configuration of <AisInstantSearch :widgets :configuration> in your example probably expect a different form of an Algolia client.

Have you tried implementing it like following:

https://github.com/nuxt-modules/algolia/blob/main/playground/pages/index.vue
